#### 성능지표 - 분류
- 정확도 (Accuracy) : 전체 정답에서 맞춘 정답의 수
- 정밀도 (Precision) : 모델 (예측) 기준으로 모델이 True라고 한 것이 정답(실제) True인 것
- 재현율 (Recall) : 정답(실제) 기준으로 정답(실제)이 True 라고 한 것이 모델(예측) True인 것
- F1- Score : 재현율과 정밀도 2가지를 조합한 점수
- 오차행렬 (Confusion Matrix) : 정답과 예측값의 관계를 나타내는 표

[1] 모듈로딩 및 데이터 준비

In [20]:
# 모듈로딩
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split

# sklearn에서 제공하는 모델 성능평가 관련 모듈
from sklearn.metrics import accuracy_score 

import pandas as pd
import numpy as np

In [21]:
# 데이터 로딩
digitBunch = load_digits(as_frame=True)
digitBunch

{'data':       pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
 0           0.0        0.0        5.0       13.0        9.0        1.0   
 1           0.0        0.0        0.0       12.0       13.0        5.0   
 2           0.0        0.0        0.0        4.0       15.0       12.0   
 3           0.0        0.0        7.0       15.0       13.0        1.0   
 4           0.0        0.0        0.0        1.0       11.0        0.0   
 ...         ...        ...        ...        ...        ...        ...   
 1792        0.0        0.0        4.0       10.0       13.0        6.0   
 1793        0.0        0.0        6.0       16.0       13.0       11.0   
 1794        0.0        0.0        1.0       11.0       15.0        1.0   
 1795        0.0        0.0        2.0       10.0        7.0        0.0   
 1796        0.0        0.0       10.0       14.0        8.0        1.0   
 
       pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
 0        

[2] 피쳐와 레이블 추출

In [22]:
# 0 ~ 9까지 숫자 이미지 데이터 값 
imageDF = digitBunch["data"]
imageDF

pixel_0_0  pixel_0_1  pixel_0_2  pixel_0_3  pixel_0_4  pixel_0_5  \
0           0.0        0.0        5.0       13.0        9.0        1.0   
1           0.0        0.0        0.0       12.0       13.0        5.0   
2           0.0        0.0        0.0        4.0       15.0       12.0   
3           0.0        0.0        7.0       15.0       13.0        1.0   
4           0.0        0.0        0.0        1.0       11.0        0.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        4.0       10.0       13.0        6.0   
1793        0.0        0.0        6.0       16.0       13.0       11.0   
1794        0.0        0.0        1.0       11.0       15.0        1.0   
1795        0.0        0.0        2.0       10.0        7.0        0.0   
1796        0.0        0.0       10.0       14.0        8.0        1.0   

      pixel_0_6  pixel_0_7  pixel_1_0  pixel_1_1  ...  pixel_6_6  pixel_6_7  \
0           0.0        0.0        0.0        0.0  ...        0.0        0.0   
1           0.0        0.0        0.0        0.0  ...        0.0        0.0   
2           0.0        0.0        0.0        0.0  ...        5.0        0.0   
3           0.0        0.0        0.0        8.0  ...        9.0        0.0   
4           0.0        0.0        0.0        0.0  ...        0.0        0.0   
...         ...        ...        ...        ...  ...        ...        ...   
1792        0.0        0.0        0.0        1.0  ...        4.0        0.0   
1793        1.0        0.0        0.0        0.0  ...        1.0        0.0   
1794        0.0        0.0        0.0        0.0  ...        0.0        0.0   
1795        0.0        0.0        0.0        0.0  ...        2.0        0.0   
1796        0.0        0.0        0.0        2.0  ...        8.0        0.0   

      pixel_7_0  pixel_7_1  pixel_7_2  pixel_7_3  pixel_7_4  pixel_7_5  \
0           0.0        0.0        6.0       13.0       10.0        0.0   
1           0.0        0.0        0.0       11.0       16.0       10.0   
2           0.0        0.0        0.0        3.0       11.0       16.0   
3           0.0        0.0        7.0       13.0       13.0        9.0   
4           0.0        0.0        0.0        2.0       16.0        4.0   
...         ...        ...        ...        ...        ...        ...   
1792        0.0        0.0        2.0       14.0       15.0        9.0   
1793        0.0        0.0        6.0       16.0       14.0        6.0   
1794        0.0        0.0        2.0        9.0       13.0        6.0   
1795        0.0        0.0        5.0       12.0       16.0       12.0   
1796        0.0        1.0        8.0       12.0       14.0       12.0   

      pixel_7_6  pixel_7_7  
0           0.0        0.0  
1           0.0        0.0  
2           9.0        0.0  
3           0.0        0.0  
4           0.0        0.0  
...         ...        ...  
1792        0.0        0.0  
1793        0.0        0.0  
1794        0.0        0.0  
1795        0.0        0.0  
1796        1.0        0.0  

[1797 rows x 64 columns]

In [23]:
# 0~9 Label
labelSR = digitBunch["target"]
labelSR.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
# => 2진 분류를 위해서 7과 나머지 라벨 변경
## 레이블을 7인걸 찾아서 마스크 생성
(labelSR == 7).sum() # 개수확인

179

In [25]:
# 7을 제외한 나머지들은 0으로 변경, 7은 1로 변경
# 기존의 1의 값이 있으므로 전체 값을 0으로 변경 후, 7만 1로 변경
mask = (labelSR == 7)
labelSR[~mask] = 0

In [26]:
labelSR

0       0
1       0
2       0
3       0
4       0
       ..
1792    0
1793    0
1794    0
1795    0
1796    0
Name: target, Length: 1797, dtype: int32

In [27]:
# 혹시 모르니 값의 개수 확인
labelSR.value_counts()

target
0    1618
7     179
Name: count, dtype: int64

In [28]:
# 값이 7인 애들을 1로 변경
labelSR[mask] = 1

In [29]:
# 최종적인 값의 개수 확인
labelSR.value_counts()

target
0    1618
1     179
Name: count, dtype: int64

[3] 학습용 데이터셋 준비

In [30]:
X_train, X_test, y_train, y_test = train_test_split(imageDF, labelSR, stratify=labelSR, random_state=1)

In [31]:
y_train.value_counts()

target
0    1213
1     134
Name: count, dtype: int64

In [37]:
# 비율(개수) 확인하기
# 암기하기
print("[Train]", y_train.value_counts()/y_train.shape[0])
print()
print("[Test]", y_test.value_counts()/y_test.shape[0])

[Train] target
0    0.90052
1    0.09948
Name: count, dtype: float64

[Test] target
0    0.9
1    0.1
Name: count, dtype: float64


In [33]:
print(labelSR.value_counts())

target
0    1618
1     179
Name: count, dtype: int64


[4] 클래스 정의 

In [38]:
# 사용자 정의 클래스 DummyClass : 아무것도 하지 않는 클래스, 단순 테스트용
from sklearn.base import BaseEstimator 

class MyClassifier(BaseEstimator) :

    def fit(self, X, y) : pass

    def predict(self, X) : return np.zeros((len(X), 1), dtype = bool)           # zeros: 0으로 값을 채움, 무슨 값을 입력하던 결과값을 False로 취급


[5] 학습 진행

In [39]:
# 인스턴스 생성
model = MyClassifier()

# 학습
model.fit(X_train, y_train)

[6] 예측 및 성능평가

In [40]:
pre_ = model.predict(X_train)
pre_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

[6-1] 정확도 : 맞춘 개수/전체 개수 
  - ==> 불균형 데이텅니 경우 신뢰 불가 

In [42]:
accuracy_score(y_train, pre_)

0.9005196733481812

[6-2] 오차 행렬

In [43]:
from sklearn.metrics import confusion_matrix, classification_report

In [51]:
y_test = [0,0,0,1,1, 1, 0,0,0, 1, 1,1,1,0,0, 0,0,0,0,0]
y_pre = [1,1,1,1,1, 1, 0,1,0,1, 1,1,1,0,0, 0,0,0,0,0]

In [57]:
# 정답과 예측값 전달 ?
confusion_matrix(y_test, y_pre) # y정답, 예측값 : pre_

array([[9, 4],
       [0, 7]], dtype=int64)

In [58]:
# 정답과 예측값 전달
(tn, fp, fn, tp) = confusion_matrix(y_test, y_pre).reshape(-1)

In [59]:
print(tn, fp, fn, tp)

9 4 0 7


In [60]:
confusion_matrix(y_test, y_pre)

array([[9, 4],
       [0, 7]], dtype=int64)

- 정밀도 (Precision): 모델 (예측) 중심

In [48]:
from sklearn.metrics import precision_score, recall_score

In [49]:
precision_score(y_train, pre_, zero_division=0)

0.0

- 재현율(Recall) : 정답(실제) 중심

In [50]:
from sklearn.metrics import recall_score

recall_score(y_train, pre_)

0.0