In [1]:
import numpy as np

In [2]:
v = np.array([1, 2, 3, 4, 5])

In [4]:
v[0]

1

In [5]:
v[-1]

5

In [7]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [8]:
A[0]

array([1, 2, 3, 4, 5])

In [10]:
A[-1]

array([ 6,  7,  8,  9, 10])

In [12]:
B = np.arange(9).reshape(3,3)

In [14]:
B

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
B.shape

(3, 3)

In [17]:
B[0,:]

array([0, 1, 2])

In [18]:
B[0]

array([0, 1, 2])

In [20]:
B[:, 0]

array([0, 3, 6])

In [22]:
A = np.arange(1, 60, 5).reshape(3, 4)

A

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [24]:
A[...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

In [26]:
A[:2, ...]

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36]])

In [28]:
A[..., :2]

array([[ 1,  6],
       [21, 26],
       [41, 46]])

In [29]:
# 논리식 검색과 팬시검색
# 논리 검색: 논리식을 평가한 후에 참인 경우의 원소만을 검색하는 것

In [34]:
import random

L = np.random.randn(7,4)

L

array([[-1.1212539 ,  0.82460433, -1.1557496 ,  0.70890464],
       [-0.40820092,  0.13114819,  1.18625732,  1.3681648 ],
       [ 1.11008792,  0.15819416, -0.30063419, -0.14421754],
       [ 0.61231547,  0.21133989,  0.17193413,  0.91885161],
       [ 1.27418621,  0.35838578, -0.09534602,  2.98646561],
       [-1.29197485,  0.40062367,  0.83699503,  1.60474344],
       [-0.06426376, -0.48124736, -0.81143247, -0.54663647]])

In [36]:
L[L<0]

array([-1.1212539 , -1.1557496 , -0.40820092, -0.30063419, -0.14421754,
       -0.09534602, -1.29197485, -0.06426376, -0.48124736, -0.81143247,
       -0.54663647])

In [38]:
L[L<0] = 999

L

array([[9.99000000e+02, 8.24604328e-01, 9.99000000e+02, 7.08904642e-01],
       [9.99000000e+02, 1.31148185e-01, 1.18625732e+00, 1.36816480e+00],
       [1.11008792e+00, 1.58194155e-01, 9.99000000e+02, 9.99000000e+02],
       [6.12315468e-01, 2.11339892e-01, 1.71934128e-01, 9.18851606e-01],
       [1.27418621e+00, 3.58385782e-01, 9.99000000e+02, 2.98646561e+00],
       [9.99000000e+02, 4.00623675e-01, 8.36995033e-01, 1.60474344e+00],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02]])

In [40]:
LC = L[L ==999]

LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.])

In [44]:
# 논리검색은 AND, OR, NOT 연산자를 사용하지 못함
L = np.arange(0,12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [46]:
try:
    L and L
except Exception as e :
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [48]:
np.logical_and(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [50]:
L[np.logical_and(L,L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
X = np.arange(16).reshape(4,4)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
X[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [56]:
X[[1,2], [2,3]]

array([ 6, 11])

In [59]:
type(np.ix_)

numpy._ArrayFunctionDispatcher

In [60]:
a[np.ix_([0,1], [0,1])]

array([[2, 3],
       [8, 9]])

In [61]:
a = np.array([[2,3,4,5], [8,9,0,1]])
a

array([[2, 3, 4, 5],
       [8, 9, 0, 1]])

In [64]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
x[0, [0,1]]

array([0, 1])

In [68]:
x[1, [0,1]]

array([5, 6])

In [70]:
x[[0,1]]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
x[[0,1], 0]

array([0, 5])

In [ ]:
# 배열보다 작게 조회

In [74]:
X = np.arange(9).reshape(3,3)
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
a = X[1:, 1:]
a

array([[4, 5],
       [7, 8]])

In [81]:
np.may_share_memory(X,a)

True

In [82]:
# 배열보다 크게 조회
a = np.reshape(np.arange(10), (2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [83]:
c = a[[1,1,1], np.newaxis]
c.shape

(3, 1, 5)

In [84]:
# 메소드나 함수로 검색하기

In [86]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [88]:
x.item(1)

1

In [90]:
x.item(5)

5

In [92]:
x.item(1,2)

5

In [94]:
x.item((2,2))

8

In [96]:
x.item(2,2)

8

In [98]:
x.itemset(2,20) # 2를 20으로 변경
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [101]:
x.itemset((1,2), 20) # (1,2)f를 20으로 변경
x

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [102]:
x.view()

array([[ 0,  1, 20],
       [ 3,  4, 20],
       [ 6,  7,  8]])

In [105]:
b = np.linspace(1, 10, 10).reshape(2,5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [107]:
posl = [3,4]
b.take(posl)

array([4., 5.])

In [109]:
pos2 = [[0,1], [3,4]]
b.take(pos2)

array([[1., 2.],
       [4., 5.]])

In [111]:
c = b.copy()
np.may_share_memory(c,b)

False

In [113]:
c.put(posl, 30)
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [115]:
c.put(posl, [50,50])
c

array([[ 1.,  2.,  3., 50., 50.],
       [ 6.,  7.,  8.,  9., 10.]])

In [117]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [119]:
np.choose(0,x)

array([0, 1, 2])

In [121]:
np.choose([0], x)

array([0, 1, 2])

In [122]:
np.choose(tuple([0,1,2]), x)

array([0, 4, 8])

In [124]:
np.choose(tuple([2,1,0]),x)

array([6, 4, 2])

In [ ]:
# numpy where은 조건식 판단을 검색에 넣어 조회가 가능
# -> select, extract

In [126]:
np.where(x>4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [128]:
x[np.where(x>4)]

array([5, 6, 7, 8])

In [130]:
a = np.select(x>5, x*2)
a

array([12, 14, 16])

In [132]:
np.extract(x>4, x)

array([5, 6, 7, 8])

In [ ]:
# 다차원 배열의 연산
