#### Image Drawing
- 이미지 객체 ndarray 준비 필요

In [1]:
# Module Loading
import cv2
import numpy as np

In [2]:
# Data 관련 변수 설정
DIR_PATH = "../image/"

In [3]:
# Image 객체
bg_data = np.full((500, 500, 3), 255)           # BGR 값 255: 화이트, 0 : 검은색

# Image File 생성
BG_FILE = DIR_PATH+"white_bg.jpg"
cv2.imwrite(BG_FILE, bg_data)                   # 도화지를 이미지 파일로 만든 것

True

In [4]:
print(bg_data)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [5]:
# 도화지 이미지 가져오기
white_bg = cv2.imread(BG_FILE)
white_bg.shape, white_bg.ndim

((500, 500, 3), 3)

In [6]:
# 선 그리기
cv2.line(white_bg, (50, 50), (250, 250), 0)     # 마지막 0은 선의 색깔
cv2.imshow("DRAWING", white_bg)                 # 첫번째는 창 이름
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
cv2.line(white_bg, (50, 50), (250, 250), (255, 0 , 0), 5)           # 좌표값의 중점은 왼쪽 젤 끝지점
cv2.line(white_bg, (100, 50), (250, 250), (0, 255 , 0), 10)
cv2.line(white_bg, (150, 50), (250, 450), (100, 185 , 255), 35)

cv2.imshow("DRAWING", white_bg)                   
cv2.waitKey()
cv2.destroyAllWindows()

In [8]:
# 사각형 그리기
# ==> 대각선 두 점만 알면 사격형을 그릴 수 있음
# 선두께 -1 지정하면 채우기가 됨

cv2.rectangle(white_bg, (50, 50), (120, 300), (0, 255, 255), 4)
cv2.imshow("DRAWING", white_bg)                   
cv2.waitKey()
cv2.destroyAllWindows()

In [9]:
# 사각형 그리기
# 선두께 -1 지정하면 채우기가 됨

cv2.rectangle(white_bg, (50, 50), (120, 300), (0, 255, 255), -1)
cv2.imshow("DRAWING", white_bg)                   
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
# cv2.line(white_bg, (20,40),(20,100), (255,0,0), 5)
# cv2.line(white_bg, (20,100),(60,100), (255,0,0), 5)
# cv2.line(white_bg, (60,40),(60,100), (255,0,0), 5)
# cv2.line(white_bg, (20,80),(60,80), (255,0,0), 5)


# cv2.line(white_bg, (90,40),(90,100), (255,0,0), 5)
# cv2.line(white_bg, (90,80),(110,80), (255,0,0), 5)


# cv2.line(white_bg, (120,40),(120,100), (255,0,0), 5)
# cv2.line(white_bg, (120,100),(180,100), (255,0,0), 5)
# cv2.line(white_bg, (180,40),(180,100), (255,0,0), 5)
# cv2.line(white_bg, (120,80),(180,80), (255,0,0), 5)



# cv2.line(white_bg, (160,100),(160,150), (255,0,0), 5)
# cv2.line(white_bg, (125,150),(180,150), (255,0,0), 5)

# cv2.imshow('to. 김황선', white_bg)
# cv2.waitKey()
# cv2.destroyAllWindows()