#### 피쳐 전처리
- 수치형 피쳐 전처리 ==> 스케일링
- 범주형 피쳐 전처리 ==> 인코딩

In [1]:
# 모듈로딩
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ["TV", "냉장고", "선풍기", "에어컨"]

In [3]:
# 라벨/정수 인코더 인스턴스 생성
lencoder = LabelEncoder()

In [4]:
# 라벨/정수 인코더의 범위 및 맵핑 작업
lencoder.fit(items)

LabelEncoder()

In [5]:
# 라벨/정수값으로 변환
lencoder.transform(items)

array([0, 1, 2, 3])

### One-Hot Encoding

In [6]:
### One-Hot Encoding 원핫인코더 모듈 로딩
from sklearn.preprocessing import OneHotEncoder

In [9]:
# 인코더 인스턴스 생성
ohEncoder = OneHotEncoder()

In [10]:
# 원핫 인코더의 범위 및 맨핍 작업
# fit 안에 2D 값을 저장해야함
ohEncoder.fit([items])

OneHotEncoder()

In [14]:
# 원핫 인코딩으로 변환
ohEncoder.transform([items])
# 결과값을 보여주지 않음 => 풀어서 봐야함

<1x4 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [16]:
oh_items = ohEncoder.transform([items])
type(oh_items)

scipy.sparse._csr.csr_matrix

In [17]:
oh_items.toarray()

array([[1., 1., 1., 1.]])

In [21]:
## numpy로 2차원 만들어서 값 구하기

In [18]:
import numpy as np

In [19]:
arr_items = np.array(items) # 1차원
arr_items = np.array(items).reshape(-1, 1) # 2차원

print(arr_items)

[['TV']
 ['냉장고']
 ['선풍기']
 ['에어컨']]


In [20]:
ohEncoder.fit(arr_items)

OneHotEncoder()

In [22]:
oh_items = ohEncoder.transform(arr_items)
type(oh_items)

scipy.sparse._csr.csr_matrix

In [23]:
oh_items.toarray()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 정수 인코딩 ==> 범주형 feature 

In [24]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
# 타이타닉 자료를 예시
data = [["male", "C", "child"], ["female", "S", "child"]] 

In [30]:
# 정수인코더 인스턴스 생성
odEncoder = OrdinalEncoder()

# 정수 인코딩 범위 및 맵핑 진행
odEncoder.fit(data) # fit(2D)

OrdinalEncoder()

In [32]:
# 범주 피처 -> 정수 피쳐 변환
odEncoder.transform(data)

# man, female 중에서 알파벳 순으로 하면 f가 먼저 -> female 0
# c, s증에 c가 먼저 -> c = 0
# child, child는 동일 값 -> 0

array([[1., 0., 0.],
       [0., 1., 0.]])