In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from urllib.parse import quote
import time
import csv
import pandas as pd
from selenium.webdriver.support import expected_conditions as EC
import os
import time
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests
import collections
from requests.exceptions import ConnectionError
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager  # Chrome driver 자동 업데이트
from selenium.webdriver.common.by import By  # find element 사용
import time
import re

<hr>

In [2]:
japan = pd.read_csv(r"C:\Hwan\Application_WEB\project\recipes2.csv")

In [3]:
JDF = pd.DataFrame(japan)
JDF

음식명                소제목                            재료  \
0          배 새우 두부 무침        고소한 소스를 곁들인                         배\n¼개   
1         반건조 오징어 온소바       입에 착 감기는 쫄깃함                  반건조 오징어\n1마리   
2          전복 시소말이 튀김        향긋한 시소잎을 돌돌                       전복\n2마리   
3               금태 술찜       가쓰오 다시로 맛을 낸                       금태\n1마리   
4           물오징어 빵꼬아게        빵가루를 묻혀 튀겨낸                     물오징어\n1마리   
5            낫토 산마 소바      면과 함께 즐기는 건강식                     소바 면\n80g   
6            옥도미 맑은 국           담백하고 개운한                      옥도미\n1마리   
7            고기 수박 우동      수박의 흰 부분을 이용한                 소고기 샤브용\n100g   
8               찬 잣소면          갖은 재료를 올린                       소면\n80g   
9           고등어 미소 조림           구수하고 달큰한                고등어\n1마리(300g)   
10               스키야키       노른자에 찍어먹는 별미  소고기 등심(0.5cm 두께로 자른 것)\n300g   
11              미소 시루        일식의 기본 국물요리                       다시마\n2장   
12               야끼소바         LG 인덕션 레시피              야끼소바면\n2봉지(300g)   
13  된장 버터 옥수수라면(짱구라면)  <짱구는 못 말려> 라면 레시피             인스턴트 라면(사리곰탕)\n2개   
14          대파 닭고기 우동           폴킴이 알려주는                       우동면\n2개   
15             붓카케 우동      탱글탱글! 차가운 면발!                       우동면\n2개   
16              영귤 소바          깔끔하면서 상큼한                        영귤\n6개   
17             단호박 양갱        견과류를 넣어 고소한                     단호박\n200g   
18         연어 아보카도 덮밥         초간단 혼밥 메뉴!                 연어 (횟감)\n200g   
19            유자 삼치조림           색다른 조림요리                       삼치\n1마리   
20              연어달걀찜          고급스러운 비주얼                        달걀\n4개   
21               타코야끼          겨울 간식 최강자                      문어\n120g   
22              고등어덮밥       근사하고 정갈한 한 끼                    순살 고등어\n2쪽   
23              어묵 전골         호호~불어가며 먹는                    모듬어묵\n500g   
24           튀김덮밥(텐동)        보기만해도 행복해지는                      생새우\n6마리   
25              쇠고기덮밥      식감 살려 더욱 맛있어요               쇠고기(불고기용)\n200g   
26              치즈돈가스        풍부한 치즈맛에 퐁당          돼지고기(등심 또는 안심)\n400g   
27           일본식 두부튀김          간단하지만 폼나는                   두부(찌개용)\n1모   
28            고등어간장조림         비린내 없이 깔끔한                  손질한 고등어\n2마리   
29       새우크림카레(에비카레)          부드럽고 진한 맛                     고형카레\n4조각   
30               장어덮밥        보약이 따로 필요없는                       장어\n2마리   
31              돈가스덮밥      속을 가득 채우는 든든함                    시판 돈가스\n1개   
32           나폴리탄스파게티           달큰한 토마토향                   스파게티면\n150g   
33          연어장과 연어덮밥      첫 숟가락부터 반하게 될                     생연어\n600g   
34             야끼스파게티         가츠오부시가 춤추는                   스파게티면\n130g   
35             치킨가라아게             육즙 가득한                    닭다리살\n300g   
36           두부가츠샌드위치      겉은 바삭 속은 부드러운                        식빵\n4장   
37             연어오차즈케          녹차의 향기 싣고                        밥\n1공기   

                                                   링크  
0   https://wtable.co.kr/recipes/1x8u5iLqzVJ4EcoX2...  
1   https://wtable.co.kr/recipes/BgKLcY6nDv38rs29p...  
2   https://wtable.co.kr/recipes/VhwzqXD6kKegSD3MH...  
3   https://wtable.co.kr/recipes/uzY3NTnA1sskskdrX...  
4   https://wtable.co.kr/recipes/z8t81CMj4Y2Gn6NsV...  
5   https://wtable.co.kr/recipes/TsBrJYFQt53wiJeUQ...  
6   https://wtable.co.kr/recipes/E9KLkhjdNgCwFWQxH...  
7   https://wtable.co.kr/recipes/QtjWfpbABttvmkFJc...  
8   https://wtable.co.kr/recipes/hciM3ciYRzLahQf6j...  
9   https://wtable.co.kr/recipes/ik8VdNeXGH6GNUSbg...  
10  https://wtable.co.kr/recipes/6Kn5hmWCFQKb7xhea...  
11  https://wtable.co.kr/recipes/v25KBndcuuk4sdjGb...  
12  https://wtable.co.kr/recipes/zRwd7VXL6Rp7aoSjp...  
13  https://wtable.co.kr/recipes/ynRji9pg8McpHMchY...  
14  https://wtable.co.kr/recipes/ZQ1u19nBCyPAxjxhW...  
15  https://wtable.co.kr/recipes/99ET9LQ448Pv1pt9W...  
16  https://wtable.co.kr/recipes/o68rWb7ZFEp2soHhy...  
17  https://wtable.co.kr/recipes/QY5yohubRx9KeCpFX...  
18  https://wtable.co.kr/recipes/B2yYCMiL8iiJ1nQJq...  
19  https:/

In [4]:
JDF = JDF.drop(columns="재료")
JDF

음식명                소제목  \
0          배 새우 두부 무침        고소한 소스를 곁들인   
1         반건조 오징어 온소바       입에 착 감기는 쫄깃함   
2          전복 시소말이 튀김        향긋한 시소잎을 돌돌   
3               금태 술찜       가쓰오 다시로 맛을 낸   
4           물오징어 빵꼬아게        빵가루를 묻혀 튀겨낸   
5            낫토 산마 소바      면과 함께 즐기는 건강식   
6            옥도미 맑은 국           담백하고 개운한   
7            고기 수박 우동      수박의 흰 부분을 이용한   
8               찬 잣소면          갖은 재료를 올린   
9           고등어 미소 조림           구수하고 달큰한   
10               스키야키       노른자에 찍어먹는 별미   
11              미소 시루        일식의 기본 국물요리   
12               야끼소바         LG 인덕션 레시피   
13  된장 버터 옥수수라면(짱구라면)  <짱구는 못 말려> 라면 레시피   
14          대파 닭고기 우동           폴킴이 알려주는   
15             붓카케 우동      탱글탱글! 차가운 면발!   
16              영귤 소바          깔끔하면서 상큼한   
17             단호박 양갱        견과류를 넣어 고소한   
18         연어 아보카도 덮밥         초간단 혼밥 메뉴!   
19            유자 삼치조림           색다른 조림요리   
20              연어달걀찜          고급스러운 비주얼   
21               타코야끼          겨울 간식 최강자   
22              고등어덮밥       근사하고 정갈한 한 끼   
23              어묵 전골         호호~불어가며 먹는   
24           튀김덮밥(텐동)        보기만해도 행복해지는   
25              쇠고기덮밥      식감 살려 더욱 맛있어요   
26              치즈돈가스        풍부한 치즈맛에 퐁당   
27           일본식 두부튀김          간단하지만 폼나는   
28            고등어간장조림         비린내 없이 깔끔한   
29       새우크림카레(에비카레)          부드럽고 진한 맛   
30               장어덮밥        보약이 따로 필요없는   
31              돈가스덮밥      속을 가득 채우는 든든함   
32           나폴리탄스파게티           달큰한 토마토향   
33          연어장과 연어덮밥      첫 숟가락부터 반하게 될   
34             야끼스파게티         가츠오부시가 춤추는   
35             치킨가라아게             육즙 가득한   
36           두부가츠샌드위치      겉은 바삭 속은 부드러운   
37             연어오차즈케          녹차의 향기 싣고   

                                                   링크  
0   https://wtable.co.kr/recipes/1x8u5iLqzVJ4EcoX2...  
1   https://wtable.co.kr/recipes/BgKLcY6nDv38rs29p...  
2   https://wtable.co.kr/recipes/VhwzqXD6kKegSD3MH...  
3   https://wtable.co.kr/recipes/uzY3NTnA1sskskdrX...  
4   https://wtable.co.kr/recipes/z8t81CMj4Y2Gn6NsV...  
5   https://wtable.co.kr/recipes/TsBrJYFQt53wiJeUQ...  
6   https://wtable.co.kr/recipes/E9KLkhjdNgCwFWQxH...  
7   https://wtable.co.kr/recipes/QtjWfpbABttvmkFJc...  
8   https://wtable.co.kr/recipes/hciM3ciYRzLahQf6j...  
9   https://wtable.co.kr/recipes/ik8VdNeXGH6GNUSbg...  
10  https://wtable.co.kr/recipes/6Kn5hmWCFQKb7xhea...  
11  https://wtable.co.kr/recipes/v25KBndcuuk4sdjGb...  
12  https://wtable.co.kr/recipes/zRwd7VXL6Rp7aoSjp...  
13  https://wtable.co.kr/recipes/ynRji9pg8McpHMchY...  
14  https://wtable.co.kr/recipes/ZQ1u19nBCyPAxjxhW...  
15  https://wtable.co.kr/recipes/99ET9LQ448Pv1pt9W...  
16  https://wtable.co.kr/recipes/o68rWb7ZFEp2soHhy...  
17  https://wtable.co.kr/recipes/QY5yohubRx9KeCpFX...  
18  https://wtable.co.kr/recipes/B2yYCMiL8iiJ1nQJq...  
19  https://wtable.co.kr/recipes/h1TurUwv2HZc4bFSr...  
20  https://wtable.co.kr/recipes/fwAphDQzbH8SXTpNc...  
21  https://wtable.co.kr/recipes/P2vQNRh6uhP2mc5bS...  
22  https://wtable.co.kr/recipes/1p89E4q79WvuoGRKF...  
23  https://wtable.co.kr/recipes/b5gvy3pyxt5ySWbNo...  
24  https://wtable.co.kr/recipes/JDcKtRnopd3LKKkak...  
25  https://wtable.co.kr/recipes/JzC4jiBFnF8Sor9Ne...  
26  https://wtable.co.kr/recipes/aUGL7RjpWVuZikZks...  
27  https://wtable.co.kr/recipes/tD1NBr1ufXyi5B8u4...  
28  https://wtable.co.kr/recipes/3tce64hqLnNUmkCSB...  
29  https://wtable.co.kr/recipes/SfL7dE6Wzo8YorByS...  
30  https://wtable.co.kr/recipes/p9DQF4cEGaUV9rxmX...  
31  https://wtable.co.kr/recipes/p7tbwekBzoEV1sSVR...  
32  https://wtable.co.kr/recipes/FfMJXpGayqCNf7wEq...  
33  https://wtable.co.kr/recipes/1HGYZE7L4CV1FxFqL...  
34  https://wtable.co.kr/recipes/jEE71yJ1WQmyUnbvx...  
35  https://wtable.co.kr/recipes/cJkmF5qPUDo79HbW4...  
36  https://wtable.co.kr/recipes/hhR3EHeGerM8HDNM4...  
37  https://wtable.co.kr/recipes/gcPDXcjdTDKvPNWDK...

In [5]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from urllib.parse import quote
import time
import csv
import pandas as pd
from selenium.webdriver.support import expected_conditions as EC

In [6]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from urllib.parse import quote
import time
import csv
import pandas as pd
from selenium.webdriver.support import expected_conditions as EC

In [7]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait
from urllib.parse import quote
import time
import csv
import pandas as pd
from selenium.webdriver.support import expected_conditions as EC

In [8]:
import os
import time
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests
import collections
from requests.exceptions import ConnectionError
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager  # Chrome driver 자동 업데이트
from selenium.webdriver.common.by import By  # find element 사용
import time
import re

In [9]:
import os
import time
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests
import collections
from requests.exceptions import ConnectionError
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager  # Chrome driver 자동 업데이트
from selenium.webdriver.common.by import By  # find element 사용
import time
import re

In [10]:
import os
import time
from bs4 import BeautifulSoup
from urllib.request import urlopen
import requests
import collections
from requests.exceptions import ConnectionError
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager  # Chrome driver 자동 업데이트
from selenium.webdriver.common.by import By  # find element 사용
import time
import re

In [11]:
JDF.tail()

음식명            소제목  \
33  연어장과 연어덮밥  첫 숟가락부터 반하게 될   
34     야끼스파게티     가츠오부시가 춤추는   
35     치킨가라아게         육즙 가득한   
36   두부가츠샌드위치  겉은 바삭 속은 부드러운   
37     연어오차즈케      녹차의 향기 싣고   

                                                   링크  
33  https://wtable.co.kr/recipes/1HGYZE7L4CV1FxFqL...  
34  https://wtable.co.kr/recipes/jEE71yJ1WQmyUnbvx...  
35  https://wtable.co.kr/recipes/cJkmF5qPUDo79HbW4...  
36  https://wtable.co.kr/recipes/hhR3EHeGerM8HDNM4...  
37  https://wtable.co.kr/recipes/gcPDXcjdTDKvPNWDK...

- train, test 나누기

In [12]:
from sklearn.model_selection import train_test_split

X = JDF[['소제목']]
y = JDF['음식명']  

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 확인
print(f"Train 데이터 개수: {len(X_train)}")
print(f"Test 데이터 개수: {len(X_test)}")
print(f"총 Data 수 : {len(X_train) + len(X_test)}")

Train 데이터 개수: 30
Test 데이터 개수: 8
총 Data 수 : 38


- 구두점, 불용어 제거

In [13]:
import string

string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [14]:
# 구두점 제거 함수
def remove_punctuation(text):
    punc = string.punctuation
    # 문자열인 경우에만 구두점을 제거
    if isinstance(text, str):
        return ''.join([char for char in text if char not in punc])
    else:
        return text

In [15]:
# Train 데이터에서 구두점 제거
X_train['소제목'] = X_train['소제목'].apply(remove_punctuation)

# Test 데이터에서 구두점 제거
X_test['소제목'] = X_test['소제목'].apply(remove_punctuation)

In [16]:
# 결과 확인
X_train.head(), X_test.head()

(            소제목
 24  보기만해도 행복해지는
 15  탱글탱글 차가운 면발
 17  견과류를 넣어 고소한
 8     갖은 재료를 올린
 16    깔끔하면서 상큼한,
                 소제목
 33    첫 숟가락부터 반하게 될
 36    겉은 바삭 속은 부드러운
 4       빵가루를 묻혀 튀겨낸
 13  짱구는 못 말려 라면 레시피
 30      보약이 따로 필요없는)

In [17]:
# 토큰화 
def tokenize(text):
    if isinstance(text, str):
        return text.split() 
    else:
        return []

In [18]:
from collections import Counter
# 빈도 카운트
counter = Counter()

for sentence in JDF["소제목"]:
    tokens = tokenize(sentence) 
    counter.update(tokens)  

# 단어 빈도 출력
print(counter)

# 가장 빈도가 높은 상위 5개 단어를 출력
print(counter.most_common(5))

Counter({'고소한': 2, '달큰한': 2, '레시피': 2, '소스를': 1, '곁들인': 1, '입에': 1, '착': 1, '감기는': 1, '쫄깃함': 1, '향긋한': 1, '시소잎을': 1, '돌돌': 1, '가쓰오': 1, '다시로': 1, '맛을': 1, '낸': 1, '빵가루를': 1, '묻혀': 1, '튀겨낸': 1, '면과': 1, '함께': 1, '즐기는': 1, '건강식': 1, '담백하고': 1, '개운한': 1, '수박의': 1, '흰': 1, '부분을': 1, '이용한': 1, '갖은': 1, '재료를': 1, '올린': 1, '구수하고': 1, '노른자에': 1, '찍어먹는': 1, '별미': 1, '일식의': 1, '기본': 1, '국물요리': 1, 'LG': 1, '인덕션': 1, '<짱구는': 1, '못': 1, '말려>': 1, '라면': 1, '폴킴이': 1, '알려주는': 1, '탱글탱글!': 1, '차가운': 1, '면발!': 1, '깔끔하면서': 1, '상큼한': 1, '견과류를': 1, '넣어': 1, '초간단': 1, '혼밥': 1, '메뉴!': 1, '색다른': 1, '조림요리': 1, '고급스러운': 1, '비주얼': 1, '겨울': 1, '간식': 1, '최강자': 1, '근사하고': 1, '정갈한': 1, '한': 1, '끼': 1, '호호~불어가며': 1, '먹는': 1, '보기만해도': 1, '행복해지는': 1, '식감': 1, '살려': 1, '더욱': 1, '맛있어요': 1, '풍부한': 1, '치즈맛에': 1, '퐁당': 1, '간단하지만': 1, '폼나는': 1, '비린내': 1, '없이': 1, '깔끔한': 1, '부드럽고': 1, '진한': 1, '맛': 1, '보약이': 1, '따로': 1, '필요없는': 1, '속을': 1, '가득': 1, '채우는': 1, '든든함': 1, '토마토향': 1, '첫': 1, '숟가락부터': 1, '반하게': 1, '될': 1, '가츠오부시가': 

In [19]:
# 토큰화 결과
JDF["토큰화된_소제목"] = JDF["소제목"].apply(tokenize)

TOKENDF = pd.DataFrame(JDF["토큰화된_소제목"])
TOKENDF.head()

토큰화된_소제목
0    [고소한, 소스를, 곁들인]
1  [입에, 착, 감기는, 쫄깃함]
2    [향긋한, 시소잎을, 돌돌]
3  [가쓰오, 다시로, 맛을, 낸]
4    [빵가루를, 묻혀, 튀겨낸]

- 단어사전

In [20]:
# 각 문장에 대해 토큰 빈도 카운팅
for tokens in JDF["토큰화된_소제목"]:
    counter.update(tokens)

# 단어 빈도를 기반으로 단어사전 생성 (데이터프레임으로 변환)
japan_word_dict = pd.DataFrame(counter.items(), columns=['단어', '빈도'])

# 빈도가 높은 순서대로 정렬
japan_word_dict = japan_word_dict.sort_values(by="빈도", ascending=False)

# 단어사전 
japan_word_dict.head()


단어  빈도
0   고소한   4
31  달큰한   4
40  레시피   4
56  메뉴!   2
80  폼나는   2

In [21]:
# pip install tensorflow

In [22]:
import numpy as np
from collections import Counter

# 토큰화 함수
def tokenize(text):
    if isinstance(text, str):
        return text.split()  
    else:
        return []

TokenList = JDF['소제목'].apply(tokenize).tolist()

# 모든 단어에 대한 단어사전(단어 -> 정수 매핑) 만들기
counter = Counter()
for tokens in TokenList:
    counter.update(tokens)

vocab_size = 100
most_common_words = counter.most_common(vocab_size)
word_to_index = {word: i + 1 for i, (word, _) in enumerate(most_common_words)} 
# 문장을 정수 인코딩
encoded_sentences = []
for tokens in TokenList:
    encoded_sentence = [word_to_index.get(word, 0) for word in tokens]  
    encoded_sentences.append(encoded_sentence)

# 결과 확인
print("정수 인코딩 결과 (상위 5개 문장):")
print(encoded_sentences[:5])


정수 인코딩 결과 (상위 5개 문장):
[[1, 4, 5], [6, 7, 8, 9], [10, 11, 12], [13, 14, 15, 16], [17, 18, 19]]


In [23]:
maxlen = 10

# 패딩을 추가하는 함수
def pad_sequence(sequence, maxlen):
    if len(sequence) < maxlen:
        return sequence + [0] * (maxlen - len(sequence))  # 짧으면 0을 뒤에 채움
    else:
        return sequence[:maxlen]  # 길면 자름

# 모든 문장에 패딩 적용
padded_sentences = np.array([pad_sequence(sentence, maxlen) for sentence in encoded_sentences])

# 결과 확인
print("패딩된 결과 (상위 5개 문장):")
print(padded_sentences[:5])


패딩된 결과 (상위 5개 문장):
[[ 1  4  5  0  0  0  0  0  0  0]
 [ 6  7  8  9  0  0  0  0  0  0]
 [10 11 12  0  0  0  0  0  0  0]
 [13 14 15 16  0  0  0  0  0  0]
 [17 18 19  0  0  0  0  0  0  0]]


- DataLoader

In [24]:
import torch
from torch.utils.data import Dataset, DataLoader

class TextDataset(Dataset):
    def __init__(self, data, labels):
        self.data = data 
        self.labels = labels 
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return torch.tensor(self.data[idx], dtype=torch.long), torch.tensor(self.labels[idx], dtype=torch.long)

In [25]:
# 필요한 라이브러리 임포트
import torch
from torch.utils.data import DataLoader
import torch.nn as nn
import torch.optim as optim

# TextDataset 클래스는 이미 정의되어 있으니, 이를 이용해서 학습에 필요한 데이터로더를 생성합니다.

# 데이터 준비 과정에서 정수 인코딩된 `padded_sentences`와 레이블 `y_train`, `y_test`를 이용
train_dataset = TextDataset(padded_sentences[:len(X_train)], y_train.values)
test_dataset = TextDataset(padded_sentences[len(X_train):], y_test.values)

# 데이터로더 생성
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# 간단한 모델 정의 (예시로 RNN 사용)
class SimpleRNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(SimpleRNN, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.RNN(embedding_dim, hidden_dim, batch_first=True)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        output, hidden = self.rnn(embedded)
        out = self.fc(hidden.squeeze(0))
        return out
    
from sklearn.preprocessing import LabelEncoder

# LabelEncoder를 전체 데이터에 대해 fit
label_encoder = LabelEncoder()

# 학습 데이터와 테스트 데이터를 합친 후 fit
all_labels = pd.concat([y_train, y_test], axis=0)
label_encoder.fit(all_labels)

# 각각의 라벨을 정수로 변환
y_train_encoded = label_encoder.transform(y_train)
y_test_encoded = label_encoder.transform(y_test)

# TextDataset에 인코딩된 라벨을 사용
train_dataset = TextDataset(padded_sentences[:len(X_train)], y_train_encoded)
test_dataset = TextDataset(padded_sentences[len(X_train):], y_test_encoded)

# 데이터로더 생성
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [26]:
# 라벨의 범위를 확인 (라벨의 최대값에 맞추기)
num_classes = len(label_encoder.classes_)  # 인코딩된 라벨 클래스 수 확인

# # 모델 정의 (output_dim을 라벨 클래스 수에 맞추기)
# model = SimpleRNN(vocab_size, embedding_dim, hidden_dim, num_classes)

In [27]:
print(f"Maximum train label: {y_train_encoded.max()}")
print(f"Maximum test label: {y_test_encoded.max()}")
print(f"Number of classes: {num_classes}")


Maximum train label: 37
Maximum test label: 34
Number of classes: 38


- 모델 학습

In [28]:
# # vocab_size 정의
# vocab_size = len(set([word for sentence in padded_sentences for word in sentence]))  # 고유 단어의 수

# # 모델 설정
# model = SimpleRNN(vocab_size, embedding_dim, hidden_dim, num_classes)

# embedding_dim = 100  # 단어 임베딩의 차원
# hidden_dim = 128  # RNN의 은닉층 차원
# num_classes = len(label_encoder.classes_)  # 출력 클래스의 수 (라벨의 수)

# # 모델, 손실 함수, 옵티마이저 설정
# model = SimpleRNN(vocab_size, embedding_dim, hidden_dim, num_classes)
# criterion = nn.CrossEntropyLoss()
# optimizer = optim.Adam(model.parameters(), lr=0.001)

# # 학습 루프
# n_epochs = 35

# for epoch in range(n_epochs):
#     model.train()
#     total_loss = 0
#     correct_train = 0
#     total_train = 0
    
#     for inputs, labels in train_loader:
#         optimizer.zero_grad()
#         outputs = model(inputs)
        
#         # 손실(loss) 계산
#         loss = criterion(outputs, labels)
#         loss.backward()
#         optimizer.step()
#         total_loss += loss.item()

#         # 학습 데이터의 예측 정확도 계산
#         _, predicted = torch.max(outputs, 1)
#         total_train += labels.size(0)
#         correct_train += (predicted == labels).sum().item()

#     avg_loss = total_loss / len(train_loader)
#     train_accuracy = correct_train / total_train

#     # 테스트 데이터로 평가
#     model.eval()
#     correct_test = 0
#     total_test = 0
#     with torch.no_grad():
#         for inputs, labels in test_loader:
#             outputs = model(inputs)
#             _, predicted = torch.max(outputs, 1)
#             total_test += labels.size(0)
#             correct_test += (predicted == labels).sum().item()

#     test_accuracy = correct_test / total_test

#     # 각 에포크의 loss와 accuracy 출력
#     print(f'Epoch {epoch+1}/{n_epochs}, Loss: {avg_loss:.4f}, '
#           f'Train Accuracy: {train_accuracy:.4f}, Test Accuracy: {test_accuracy:.4f}')


NameError: name 'embedding_dim' is not defined

In [37]:
# vocab_size 정의
vocab_size = len(set([word for sentence in padded_sentences for word in sentence]))  # 고유 단어의 수

embedding_dim = 100  # 단어 임베딩의 차원
hidden_dim = 128  # RNN의 은닉층 차원
num_classes = len(label_encoder.classes_)  # 출력 클래스의 수 (라벨의 수)

# 모델 설정
model = SimpleRNN(vocab_size, embedding_dim, hidden_dim, num_classes)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# 학습 루프
n_epochs = 280
for epoch in range(n_epochs):
    model.train()
    total_loss = 0
    correct_train = 0
    total_train = 0
    
    for inputs, labels in train_loader:
        optimizer.zero_grad()
        outputs = model(inputs)
        
        # 손실(loss) 계산
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()

        # 학습 데이터의 예측 정확도 계산
        _, predicted = torch.max(outputs, 1)
        total_train += labels.size(0)
        correct_train += (predicted == labels).sum().item()

    avg_loss = total_loss / len(train_loader)
    train_accuracy = correct_train / total_train

    # 테스트 데이터로 평가
    model.eval()
    correct_test = 0
    total_test = 0
    with torch.no_grad():
        for inputs, labels in test_loader:
            outputs = model(inputs)
            _, predicted = torch.max(outputs, 1)
            total_test += labels.size(0)
            correct_test += (predicted == labels).sum().item()

    test_accuracy = correct_test / total_test

    # 각 에포크의 loss와 accuracy 출력
    print(f'Epoch {epoch+1}/{n_epochs}, Loss: {avg_loss:.4f}, '
          f'Train Accuracy: {train_accuracy:.4f}, Test Accuracy: {test_accuracy:.4f}')

# 모델을 pth 파일로 저장
torch.save(model.state_dict(), 'model.pth')


Epoch 1/280, Loss: 3.6509, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 2/280, Loss: 3.5848, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 3/280, Loss: 3.5404, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 4/280, Loss: 3.5099, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 5/280, Loss: 3.4884, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 6/280, Loss: 3.4722, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 7/280, Loss: 3.4592, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 8/280, Loss: 3.4488, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 9/280, Loss: 3.4403, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 10/280, Loss: 3.4335, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 11/280, Loss: 3.4283, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 12/280, Loss: 3.4242, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 13/280, Loss: 3.4209, Train Accuracy: 0.0333, Test Accuracy: 0.0000
Epoch 14/280, Loss: 3.4182, Train Accuracy: 0.0